### ISSUE TITLE
show users which problems they have solved

### ISSUE THREAD

**Issue by oxalorg** [oxalorg/4ever-clojure#8]
- [ ] do this after we start saving user solution state
- [ ] make the problem list sortable based on solve status

**Comment by CoderPrans** [comment]
Hi,

I am working on something like this. 

when sorted as solved first. 

![Screenshot at 2021-07-10 02-26-46](https://user-images.githubusercontent.com/24974089/125135362-769dec00-e126-11eb-9269-72b47e5b5158.png)

when sorted as solved last. 

![Screenshot at 2021-07-10 02-27-11](https://user-images.githubusercontent.com/24974089/125135374-7aca0980-e126-11eb-9209-e2716902ef44.png)

Also, since the list is just an html ordered list, the number before is index not id. Should I instead show id numbers. Because in the screenshot here "Maps" shows 5 next to it, but its problem id is 10.

**Comment by oxalorg** [comment]
Thanks for working on this @CoderPrans :)

I've just merged in some changes which relate to this. You will now be able to find a `:solutions` map with `:passed` and `:failed` values. If failed tests are 0, you can assume it as solved. 

Just an idea maybe we can even show something like `2 / 3 passed` for the problems where a partial item has been solved.
